باگ فیکس 2

diff --git a/.github/workflows/scrip.yml b/.github/workflows/scrip.yml
--- a/.github/workflows/scrip.yml
+++ b/.github/workflows/scrip.yml
@@ -62,15 +62,15 @@ jobs:
 
       - name: ⬆️ Commit and Push Changes
         run: |
-          git add configs/ README.md || true
-          if git diff --staged --quiet; then
+          git fetch origin
+          git add -A
+          if git diff --cached --quiet; then
             echo "No changes detected. Skipping commit."
           else
             echo "Changes detected. Committing..."
             git commit -m "docs: Update README and config files 🤖 [skip ci]"
             echo "Pulling remote changes with rebase..."
-            git fetch origin
-            git pull --rebase origin main || { echo "Rebase failed, aborting..."; git rebase --abort; exit 1; }
+            git pull --rebase --autostash origin main || { echo "Rebase failed, aborting..."; git rebase --abort; exit 1; }
             echo "Pushing changes..."
             git push origin main || { echo "Push failed"; exit 1; }
           fi
